-- Script de Configuração Inicial do Banco de Dados Supabase (Orion 2)
-- Rode este script no "SQL Editor" do seu painel do Supabase.

-- 1. Criação da Tabela de Organizações (Inquilinos/Empresas)
CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    plan_status TEXT DEFAULT 'trial', -- 'trial', 'active', 'expired', 'cancelled'
    trial_end_date TIMESTAMPTZ DEFAULT (now() + interval '7 days'),
    messages_used INTEGER DEFAULT 0,
    use_emojis BOOLEAN DEFAULT TRUE,
    password TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Criação da Tabela de Configurações do WhatsApp Meta
CREATE TABLE IF NOT EXISTS public.whatsapp_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    phone_number_id TEXT UNIQUE,
    waba_id TEXT NOT NULL,
    access_token TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    webhook_status TEXT DEFAULT 'disconnected',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Criação da Tabela da Base de Conhecimento RAG
CREATE TABLE IF NOT EXISTS public.knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    original_name TEXT NOT NULL,
    content TEXT NOT NULL, -- O texto extraído do TXT/PDF ficará aqui
    size BIGINT NOT NULL,
    status TEXT DEFAULT 'ready',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Criação da Tabela de Sessões de Chat (Atendimento)
CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id TEXT PRIMARY KEY, -- Formato: {org_id}_{user_phone}
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    user_phone TEXT NOT NULL,
    is_human_overflow BOOLEAN DEFAULT false,
    opt_out BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_interaction TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Criação da Tabela de Mensagens 
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'model')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Row Level Security) opcional, mas seguro
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso liberais para Service Role (O Backend Express do Orion acessará sem limite)
CREATE POLICY "Enable all for service role" ON public.organizations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.whatsapp_configs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.knowledge_documents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.chat_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.messages FOR ALL USING (true) WITH CHECK (true);

-- Criar Organização Padrão para Testes e amarrar na nova estrutura
INSERT INTO public.organizations (id, name) VALUES ('00000000-0000-0000-0000-000000000000', 'Orion Master Demo') ON CONFLICT DO NOTHING;
