-- Script de Configuração ULTRA-ROBUSTA do Banco de Dados Supabase (Orion 2)
-- Rode este script no "SQL Editor" do seu painel do Supabase.

-- 1. LIMPEZA DE SEGURANÇA (Para evitar erro de "já existe")
DROP POLICY IF EXISTS "Enable all for service role" ON public.organizations;
DROP POLICY IF EXISTS "Enable all for service role" ON public.whatsapp_configs;
DROP POLICY IF EXISTS "Enable all for service role" ON public.knowledge_documents;
DROP POLICY IF EXISTS "Enable all for service role" ON public.chat_sessions;
DROP POLICY IF EXISTS "Enable all for service role" ON public.messages;
DROP POLICY IF EXISTS "Enable all for service role" ON public.team_members;
DROP POLICY IF EXISTS "Enable all for service role" ON public.whatsapp_templates;
DROP POLICY IF EXISTS "Enable all for service role" ON public.automations;
DROP POLICY IF EXISTS "Enable all for service role" ON public.campaigns;

-- 2. CRIAÇÃO DAS TABELAS (Com IF NOT EXISTS)
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    plan_status TEXT DEFAULT 'trial',
    trial_end_date TIMESTAMPTZ DEFAULT (now() + interval '7 days'),
    messages_used INTEGER DEFAULT 0,
    use_emojis BOOLEAN DEFAULT TRUE,
    password TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    whatsapp TEXT,
    address TEXT,
    contact_person TEXT,
    social_object TEXT,
    employees_count TEXT,
    product_description TEXT,
    chatbot_name TEXT
);

CREATE TABLE IF NOT EXISTS public.whatsapp_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    phone_number_id TEXT UNIQUE,
    waba_id TEXT NOT NULL,
    access_token TEXT NOT NULL,
    app_id TEXT,
    client_secret TEXT,
    display_name TEXT,
    business_category TEXT,
    description TEXT,
    profile_picture_url TEXT,
    website TEXT,
    support_email TEXT,
    is_active BOOLEAN DEFAULT true,
    webhook_status TEXT DEFAULT 'disconnected',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    original_name TEXT NOT NULL,
    content TEXT NOT NULL,
    size BIGINT NOT NULL,
    status TEXT DEFAULT 'ready',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.knowledge_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES public.knowledge_documents(id) ON DELETE CASCADE,
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(1536),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE OR REPLACE FUNCTION match_knowledge_chunks (
  query_embedding vector(1536),
  match_threshold float,
  match_count int,
  p_org_id uuid
)
RETURNS TABLE (
  id bigint,
  content text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    kc.id,
    kc.content,
    1 - (kc.embedding <=> query_embedding) AS similarity
  FROM public.knowledge_chunks kc
  WHERE kc.org_id = p_org_id
    AND 1 - (kc.embedding <=> query_embedding) > match_threshold
  ORDER BY kc.embedding <=> query_embedding
  LIMIT match_count;
$$;

CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id TEXT PRIMARY KEY,
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    user_phone TEXT NOT NULL,
    is_human_overflow BOOLEAN DEFAULT false,
    opt_out BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_interaction TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'model')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT DEFAULT 'agent',
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    language TEXT DEFAULT 'pt_BR',
    status TEXT DEFAULT 'pending',
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.automations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT DEFAULT 'draft',
    config JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    template_id UUID REFERENCES public.whatsapp_templates(id),
    audience_type TEXT,
    filters JSONB,
    status TEXT DEFAULT 'pending',
    sent_count INTEGER DEFAULT 0,
    total_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. HABILITAR SEGURANÇA
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_templates ENABLE ROW LEVEL SECURITY;

-- 4. CRIAR REGRAS NOVAMENTE
CREATE POLICY "Enable all for service role" ON public.organizations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.whatsapp_configs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.knowledge_documents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.chat_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.team_members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.whatsapp_templates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.automations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.campaigns FOR ALL USING (true) WITH CHECK (true);

-- 5. DADOS MESTRES
INSERT INTO public.organizations (id, name, owner_email) 
VALUES ('00000000-0000-0000-0000-000000000000', 'Orion Master Demo', 'demo@orion.com') 
ON CONFLICT DO NOTHING;
